# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d69c6577fca67aa46a648bdf5910a37751df65e8550b5579a60ebf39c81df6308d3d1e6185752996c8349c690917f86cb3b5b28e0b2d3989251ac5590075f444

test:
  secret_key_base: 829e885aa70ce58d80dd952420ff1b1e79c7116f3c87e57818153e4229dcdc96fbe01ffcf23077aea2b9b03146c46b1d68217e5a39aad7533dab176c4dc9b26d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
